.PHONY: clean All

All:
	@echo "----------Building project:[ wk10ex2 - Debug ]----------"
	@$(MAKE) -f  "wk10ex2.mk"
clean:
	@echo "----------Cleaning project:[ wk10ex2 - Debug ]----------"
	@$(MAKE) -f  "wk10ex2.mk" clean
