.PHONY: clean All

All:
	@echo "----------Building project:[ strsub - Debug ]----------"
	@$(MAKE) -f  "strsub.mk"
clean:
	@echo "----------Cleaning project:[ strsub - Debug ]----------"
	@$(MAKE) -f  "strsub.mk" clean
