.PHONY: clean All

All:
	@echo "----------Building project:[ sort_stud - Debug ]----------"
	@$(MAKE) -f  "sort_stud.mk"
clean:
	@echo "----------Cleaning project:[ sort_stud - Debug ]----------"
	@$(MAKE) -f  "sort_stud.mk" clean
