.PHONY: clean All

All:
	@echo "----------Building project:[ week7Lab3 - Debug ]----------"
	@$(MAKE) -f  "week7Lab3.mk"
clean:
	@echo "----------Cleaning project:[ week7Lab3 - Debug ]----------"
	@$(MAKE) -f  "week7Lab3.mk" clean
