.PHONY: clean All

All:
	@echo "----------Building project:[ lab6student - Debug ]----------"
	@$(MAKE) -f  "lab6student.mk"
clean:
	@echo "----------Cleaning project:[ lab6student - Debug ]----------"
	@$(MAKE) -f  "lab6student.mk" clean
