.PHONY: clean All

All:
	@echo "----------Building project:[ Lab4Calendar - Debug ]----------"
	@$(MAKE) -f  "Lab4Calendar.mk"
clean:
	@echo "----------Cleaning project:[ Lab4Calendar - Debug ]----------"
	@$(MAKE) -f  "Lab4Calendar.mk" clean
