.PHONY: clean All

All:
	@echo "----------Building project:[ wk10ex1 - Debug ]----------"
	@$(MAKE) -f  "wk10ex1.mk"
clean:
	@echo "----------Cleaning project:[ wk10ex1 - Debug ]----------"
	@$(MAKE) -f  "wk10ex1.mk" clean
